### ISSUE TITLE
后台管理

### ISSUE THREAD

**Issue by ccc-19990728** [YFwillmakeit/vue-medical#2]
你好,能求一下java 后台的源码么

**Comment by YFwillmakeit** [comment]
emmm，我这里找不到了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月17日(星期二) 上午8:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [YFwillmakeit/vue-medical] 后台管理 (Issue #2)





 
你好,能求一下java 后台的源码么

**Comment by ccc-19990728** [comment]
好的吧,没事,谢谢

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YFwillmakeit/vue-medical"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月17日(星期二) 上午8:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YFwillmakeit/vue-medical] 后台管理 (Issue #2)





 emmm，我这里找不到了 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2022年5月17日(星期二) 上午8:48 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;;  
 主题: [YFwillmakeit/vue-medical] 后台管理 (Issue #2) 
 
 
 
 
 
   
 你好,能求一下java 后台的源码么
